import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const BRANCHES = ['Computer Science & Engineering', 'Computer Engineering', 'Electronics & Communication', 'Electrical Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Chemical Engineering', 'Biotechnology', 'Mathematics & Computing', 'Business Administration', 'Architecture'];
const HOSTELS = { Male: ['Hostel H', 'Hostel J', 'Hostel K', 'Hostel M'], Female: ['Hostel A', 'Hostel B', 'Hostel C', 'Hostel G'] };
const defaultPreferences = { roomType: 'Double', roommateYear: 'Any year', food: 'No preference', sleep: 'Flexible', wake: '7:00 AM', clean: 'Balanced', study: 'Balanced', noise: 'Medium', interests: ['Music', 'Reading'] };
const student = (name, gender, year, branch, hostel, avatar, color, preferences) => ({ name, gender, year, branch, hostel, avatar, color, bio: 'Looking for a kind, respectful person to share a calm and friendly room with.', preferences });
const students = [
  student('Aarav Sharma', 'Male', '2nd year', 'Computer Engineering', 'Hostel H', 'AS', '#e0d4ff', { ...defaultPreferences, sleep: 'Early bird', wake: '6:30 AM', clean: 'Very tidy', interests: ['Football', 'Music', 'Reading'] }),
  student('Kabir Mehta', 'Male', '2nd year', 'Computer Science & Engineering', 'Hostel J', 'KM', '#ffddc8', { ...defaultPreferences, sleep: 'Night owl', wake: '8:30 AM', study: 'Quiet focus', interests: ['Gym', 'Movies', 'Music'] }),
  student('Vihaan Gupta', 'Male', '1st year', 'Electronics & Communication', 'Hostel H', 'VG', '#bae4dc', { ...defaultPreferences, sleep: 'Flexible', noise: 'High', interests: ['Gaming', 'Music', 'Movies'] }),
  student('Rohan Kapoor', 'Male', '3rd year', 'Mechanical Engineering', 'Hostel K', 'RK', '#c8dcff', { ...defaultPreferences, clean: 'Very tidy', study: 'Quiet focus', interests: ['Cricket', 'Reading', 'Travel'] }),
  student('Ananya Gupta', 'Female', '2nd year', 'Computer Engineering', 'Hostel A', 'AG', '#ead2ff', { ...defaultPreferences, sleep: 'Early bird', wake: '6:30 AM', clean: 'Very tidy', interests: ['Reading', 'Music', 'Cooking'] }),
  student('Ishita Kapoor', 'Female', '2nd year', 'Computer Science & Engineering', 'Hostel B', 'IK', '#ffd8c7', { ...defaultPreferences, sleep: 'Night owl', wake: '9:00 AM', interests: ['Movies', 'Music', 'Travel'] }),
  student('Meher Bansal', 'Female', '1st year', 'Electronics & Communication', 'Hostel A', 'MB', '#c3e9df', { ...defaultPreferences, noise: 'High', interests: ['Gaming', 'Music', 'Movies'] }),
  student('Kavya Singh', 'Female', '3rd year', 'Mechanical Engineering', 'Hostel C', 'KS', '#cbdcff', { ...defaultPreferences, study: 'Quiet focus', interests: ['Cricket', 'Reading', 'Travel'] }),
];

function getScore(profile, person) {
  const a = profile.preferences, b = person.preferences;
  const checks = [a.sleep === b.sleep, a.clean === b.clean, a.study === b.study, a.noise === b.noise, a.food === b.food, a.roommateYear === 'Any year' || a.roommateYear === person.year];
  const shared = a.interests.filter(item => b.interests.includes(item)).length;
  return Math.min(98, Math.max(62, 64 + checks.filter(Boolean).length * 5 + shared * 4 + (profile.hostel === person.hostel ? 3 : 0)));
}

function App() {
  const [screen, setScreen] = useState('welcome');
  const [authMode, setAuthMode] = useState('signup');
  const [onboardStep, setOnboardStep] = useState(0);
  const [profile, setProfile] = useState({ name: 'Rishabh Sand', gender: 'Male', year: '1st year', branch: 'Computer Engineering', hostel: 'Hostel H', score: '94.2', bio: 'Looking for someone calm, kind, and up for late-night chai.', preferences: defaultPreferences });
  const [filter, setFilter] = useState('All');
  const [query, setQuery] = useState('');
  const [accountOpen, setAccountOpen] = useState(false);
  const [requests, setRequests] = useState(['Aarav Sharma']);
  const [connections, setConnections] = useState(['Kabir Mehta']);
  const [requestPanel, setRequestPanel] = useState(false);
  const [personModal, setPersonModal] = useState(null);
  const [toast, setToast] = useState('');
  const tell = message => { setToast(message); setTimeout(() => setToast(''), 2400); };
  const initials = profile.name.split(' ').map(word => word[0]).join('').slice(0, 2);
  const matches = useMemo(() => students.filter(person => person.gender === profile.gender).map(person => ({ ...person, compatibility: getScore(profile, person) })).sort((a, b) => b.compatibility - a.compatibility), [profile]);
  const shown = matches.filter(person => (filter === 'All' || person.hostel === filter) && person.name.toLowerCase().includes(query.toLowerCase()));
  const accept = name => { setRequests(old => old.filter(item => item !== name)); setConnections(old => old.includes(name) ? old : [...old, name]); setRequestPanel(false); tell(`${name} is now in your chats`); };

  if (screen === 'welcome') return <Landing open={mode => { setAuthMode(mode); setScreen('auth'); }} />;
  if (screen === 'auth') return <Auth mode={authMode} setMode={setAuthMode} back={() => setScreen('welcome')} continueTo={() => setScreen(authMode === 'signup' ? 'onboard' : 'dashboard')} />;
  if (screen === 'onboard') return <Onboarding profile={profile} setProfile={setProfile} step={onboardStep} setStep={setOnboardStep} done={() => { setScreen('dashboard'); tell('Profile created — welcome to Roomies!'); }} />;

  return <main className="app-shell">
    <Sidebar screen={screen} setScreen={setScreen} profile={profile} initials={initials} open={accountOpen} setOpen={setAccountOpen} signOut={() => { setScreen('welcome'); setAccountOpen(false); }} />
    <section className="app-content">
      {screen === 'dashboard' && <Dashboard profile={profile} matches={matches} requests={requests} openRequests={() => setRequestPanel(true)} openPerson={setPersonModal} setScreen={setScreen} />}
      {screen === 'find' && <Finder profile={profile} shown={shown} filter={filter} setFilter={setFilter} query={query} setQuery={setQuery} openPerson={setPersonModal} />}
      {screen === 'chat' && <Chat connections={connections} people={students} profile={profile} />}
      {screen === 'settings' && <Settings profile={profile} setProfile={setProfile} tell={tell} />}
    </section>
    {requestPanel && <RequestPanel requests={requests} people={students} close={() => setRequestPanel(false)} accept={accept} />}
    {personModal && <ProfileModal person={personModal} profile={profile} close={() => setPersonModal(null)} connect={() => tell(`Request sent to ${personModal.name}`)} />}
    {toast && <div className="toast">✓ {toast}</div>}
  </main>;
}

function Landing({ open }) { return <main className="landing"><nav><div className="brand"><span>n</span> Roomies</div><div className="navlinks"><a>How it works</a><a>Why Roomies?</a><button className="ghost" onClick={() => open('signin')}>Sign in</button><button onClick={() => open('signup')}>Find your roommate</button></div></nav><section className="hero"><div><p className="eyebrow">MADE FOR THAPAR STUDENTS</p><h1>Your room feels better<br />with the <i>right person.</i></h1><p className="lede">Roomies helps Thaparians find a compatible roommate based on the things that actually matter: routine, room habits, hostel and vibe.</p><button className="large" onClick={() => open('signup')}>Create your profile <b>→</b></button></div><div className="hero-card"><div className="card-head"><span>YOUR BEST MATCH</span><b>96% fit</b></div><div className="match-person"><div className="avatar big">AS</div><div><h3>Aarav Sharma</h3><p>2nd year · COE · Hostel H</p></div></div><div className="chips"><em>Early riser</em><em>Football</em><em>Clean space</em></div><button className="full" onClick={() => open('signup')}>Find your match</button></div></section></main>; }

function Auth({ mode, setMode, back, continueTo }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); return <main className="auth-page"><section className="auth-card"><button className="back-link" onClick={back}>← Back to Roomies</button><div className="brand"><span>n</span> Roomies</div><p className="eyebrow">THAPAR STUDENT COMMUNITY</p><h1>{mode === 'signup' ? 'Create your account' : 'Welcome back'}</h1><p>{mode === 'signup' ? 'Start with your Thapar email. Your complete profile comes next.' : 'Sign in to see your matches and conversations.'}</p><form onSubmit={event => { event.preventDefault(); continueTo(); }}><Field label="Thapar email" value={email} onChange={setEmail} placeholder="you@thapar.edu" /><Field label="Password" type="password" value={password} onChange={setPassword} placeholder="••••••••" /><button className="full">{mode === 'signup' ? 'Continue to profile →' : 'Sign in →'}</button></form><div className="auth-switch">{mode === 'signup' ? 'Already have an account?' : 'New to Roomies?'} <button onClick={() => setMode(mode === 'signup' ? 'signin' : 'signup')}>{mode === 'signup' ? 'Sign in' : 'Create an account'}</button></div></section></main>; }

function Onboarding({ profile, setProfile, step, setStep, done }) {
  const update = (field, value) => setProfile(current => ({ ...current, [field]: value }));
  const updatePreference = (field, value) => setProfile(current => ({ ...current, preferences: { ...current.preferences, [field]: value } }));
  const titles = ['Let’s start with you.', 'Your room, your rules.', 'The little things matter.', 'Make it feel like you.'];
  const descriptions = ['We’ll use this to find people who fit your everyday life.', 'We only show hostels that are relevant to you.', 'A good roommate respects your rhythm.', 'A little personality makes matching easier.'];

  return <main className="onboard">
    <div className="on-logo"><span>n</span> Roomies <small>for Thapar</small></div>
    <div className="progress"><i style={{ width: `${(step + 1) * 25}%` }} /></div>
    <section className="form-wrap">
      <div className="form-copy"><p className="eyebrow">STEP {step + 1} OF 4</p><h1>{titles[step]}</h1><p>{descriptions[step]}</p></div>
      <div className="form-card">
        {step === 0 && <>
          <Field label="Full name" value={profile.name} onChange={value => update('name', value)} />
          <div className="two">
            <Select label="Year" value={profile.year} options={['1st year', '2nd year', '3rd year', '4th year']} onChange={value => update('year', value)} />
            <Select label="Gender" value={profile.gender} options={['Male', 'Female']} onChange={value => setProfile(current => ({ ...current, gender: value, hostel: HOSTELS[value][0] }))} />
          </div>
          <Select label="Branch" value={profile.branch} options={BRANCHES} onChange={value => update('branch', value)} />
          <Field label={profile.year === '1st year' ? 'JEE percentile' : 'CGPA'} value={profile.score} onChange={value => update('score', value)} hint="Used only to find peers in a similar academic range." />
        </>}
        {step === 1 && <>
          <div className="hostel-note">Showing {profile.gender === 'Male' ? 'boys’' : 'girls’'} hostels only</div>
          <Select label="Preferred hostel" value={profile.hostel} options={HOSTELS[profile.gender]} onChange={value => update('hostel', value)} />
          <Select label="Room type" value={profile.preferences.roomType} options={['Single', 'Double', 'No preference']} onChange={value => updatePreference('roomType', value)} />
          <Select label="Food preference" value={profile.preferences.food} options={['Vegetarian', 'Non-vegetarian', 'No preference']} onChange={value => updatePreference('food', value)} />
          <Select label="Roommate year" value={profile.preferences.roommateYear} options={['Same year', 'Any year', 'No preference']} onChange={value => updatePreference('roommateYear', value)} />
        </>}
        {step === 2 && <>
          <Select label="Sleep schedule" value={profile.preferences.sleep} options={['Early bird', 'Flexible', 'Night owl']} onChange={value => updatePreference('sleep', value)} />
          <Select label="Wake-up time" value={profile.preferences.wake} options={['5:30 AM', '6:30 AM', '7:00 AM', '8:00 AM', '9:00 AM']} onChange={value => updatePreference('wake', value)} />
          <Select label="Cleanliness" value={profile.preferences.clean} options={['Very tidy', 'Balanced', 'Relaxed']} onChange={value => updatePreference('clean', value)} />
          <Select label="Study vibe" value={profile.preferences.study} options={['Quiet focus', 'Balanced', 'Social']} onChange={value => updatePreference('study', value)} />
          <Select label="Noise tolerance" value={profile.preferences.noise} options={['Low', 'Medium', 'High']} onChange={value => updatePreference('noise', value)} />
        </>}
        {step === 3 && <>
          <Field label="A little about you" value={profile.bio} onChange={value => update('bio', value)} textarea />
          <h3>Interests</h3>
          <InterestPicker selected={profile.preferences.interests} onChange={value => updatePreference('interests', value)} />
        </>}
        <div className="form-actions">
          <button className="ghost" onClick={() => setStep(Math.max(0, step - 1))}>← Back</button>
          <button onClick={() => step < 3 ? setStep(step + 1) : done()}>{step === 3 ? 'Create profile' : 'Continue →'}</button>
        </div>
      </div>
    </section>
  </main>;
}

function Sidebar({ screen, setScreen, profile, initials, open, setOpen, signOut }) { return <aside><div className="side-brand"><span>n</span> Roomies</div><div className="side-nav"><button className={screen === 'dashboard' ? 'active' : ''} onClick={() => setScreen('dashboard')}>⌂ <span>Discover</span></button><button className={screen === 'find' ? 'active' : ''} onClick={() => setScreen('find')}>⌕ <span>Find roommates</span></button><button className={screen === 'chat' ? 'active' : ''} onClick={() => setScreen('chat')}>☏ <span>Chats</span></button><button className={screen === 'settings' ? 'active' : ''} onClick={() => setScreen('settings')}>⚙ <span>Settings</span></button></div><div className="account-wrap"><button className="account" onClick={() => setOpen(!open)}><div className="avatar">{initials}</div><div><b>{profile.name}</b><small>{profile.hostel}</small></div><span>⌄</span></button>{open && <div className="account-menu"><button onClick={() => setScreen('settings')}>⚙ Account settings</button><button className="signout" onClick={signOut}>↪ Sign out</button></div>}</div></aside>; }

function Dashboard({ profile, matches, requests, openRequests, openPerson, setScreen }) { const top = matches[0]; return <><header className="app-head"><div><p className="eyebrow">GOOD AFTERNOON, {profile.name.split(' ')[0].toUpperCase()}</p><h1>People you’ll get along with.</h1><p>Your compatibility updates every time you update your preferences.</p></div><button className="bell" onClick={openRequests}>♢{requests.length > 0 && <i />}</button></header><section className="feature-match"><div><p className="eyebrow">TOP MATCH FOR YOU</p><h2>{top.name} <span>{top.compatibility}% compatible</span></h2><p>Shared routines, room habits, and interests make this an especially strong fit.</p><div className="chips">{top.preferences.interests.slice(0, 3).map(item => <em key={item}>{item}</em>)}</div><button onClick={() => openPerson(top)}>View full profile →</button></div><div className="feature-art"><div className="avatar huge" style={{ background: top.color }}>{top.avatar}</div><div className="quote">“{top.bio}”</div></div></section><section className="section-head"><div><h2>Great fits</h2><p>Matches from your current preferences.</p></div><button className="text-button" onClick={() => setScreen('find')}>See all →</button></section><div className="card-grid">{matches.slice(1, 4).map(person => <PersonCard key={person.name} person={person} openPerson={openPerson} />)}</div></>; }

function Finder({ profile, shown, filter, setFilter, query, setQuery, openPerson }) { return <><header className="app-head compact"><div><p className="eyebrow">EXPLORE YOUR COMMUNITY</p><h1>Find your people.</h1></div></header><div className="searchbar"><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by name, branch, interest..." /></div><div className="filter-row"><b>Showing {shown.length} {profile.gender === 'Female' ? 'women' : 'men'}</b>{['All', ...HOSTELS[profile.gender]].map(hostel => <button key={hostel} className={filter === hostel ? 'selected' : ''} onClick={() => setFilter(hostel)}>{hostel}</button>)}</div><section className="near-title"><div><h2>Best fits</h2><p>Highly compatible with your lifestyle.</p></div></section><div className="card-grid">{shown.filter(person => person.compatibility >= 82).map(person => <PersonCard key={person.name} person={person} openPerson={openPerson} />)}</div><section className="near-title"><div><h2>Worth a look</h2><p>Different in a few ways, still potentially a good room fit.</p></div></section><div className="card-grid">{shown.filter(person => person.compatibility < 82).map(person => <PersonCard key={person.name} person={person} openPerson={openPerson} />)}</div></>; }

function PersonCard({ person, openPerson }) { return <article className="person-card"><div className="person-top"><div className="avatar" style={{ background: person.color }}>{person.avatar}</div><span className="score">{person.compatibility}%</span></div><h3>{person.name}</h3><p>{person.year} · {shortBranch(person.branch)}</p><p className="hostel">⌂ {person.hostel}</p><div className="chips">{person.preferences.interests.slice(0, 3).map(item => <em key={item}>{item}</em>)}</div><div className="card-actions"><button className="view" onClick={() => openPerson(person)}>View profile</button><button className="connect">Connect +</button></div></article>; }

function ProfileModal({ person, profile, close, connect }) { const prefs = person.preferences; return <div className="inbox-overlay profile-overlay"><section className="profile-modal"><header><div><p className="eyebrow">ROOMMATE PROFILE</p><h2>{person.name}</h2></div><button className="close" onClick={close}>×</button></header><div className="modal-person"><div className="avatar huge" style={{ background: person.color }}>{person.avatar}</div><div><p>{person.year} · {person.branch}</p><p>⌂ {person.hostel}</p><span className="score">{person.compatibility}% compatible with you</span></div></div><p className="bio">{person.bio}</p><h3>Room & lifestyle preferences</h3><div className="pref-grid"><Preference label="Room type" value={prefs.roomType} /><Preference label="Food" value={prefs.food} /><Preference label="Sleep style" value={prefs.sleep} /><Preference label="Wake-up time" value={prefs.wake} /><Preference label="Cleanliness" value={prefs.clean} /><Preference label="Study vibe" value={prefs.study} /><Preference label="Noise tolerance" value={prefs.noise} /><Preference label="Roommate year" value={prefs.roommateYear} /></div><h3>Interests</h3><div className="chips">{prefs.interests.map(item => <em key={item}>{item}</em>)}</div><button className="full modal-connect" onClick={() => { connect(); close(); }}>Send connection request</button></section></div>; }

function RequestPanel({ requests, people, close, accept }) { return <div className="inbox-overlay"><section className="inbox"><header><div><p className="eyebrow">CONNECTION REQUESTS</p><h2>Notifications</h2></div><button className="close" onClick={close}>×</button></header>{requests.length ? requests.map(name => { const person = people.find(item => item.name === name); return <article className="request" key={name}><div className="avatar" style={{ background: person.color }}>{person.avatar}</div><div><h3>{person.name}</h3><p>{person.compatibility || 'A strong'} compatibility match.</p><small>Sent you a connection request</small></div><div><button className="accept" onClick={() => accept(name)}>Accept</button><button className="decline" onClick={close}>Ignore</button></div></article>; }) : <div className="empty"><div>✦</div><h3>All caught up</h3><p>New requests will appear here.</p></div>}</section></div>; }

function Chat({ connections, people, profile }) { const connectedPeople = people.filter(person => connections.includes(person.name)); const [selected, setSelected] = useState(connectedPeople[0] || people[0]); const [message, setMessage] = useState(''); return <><header className="app-head compact"><div><p className="eyebrow">YOUR CONNECTIONS</p><h1>Chats</h1><p>Only accepted connections can message each other.</p></div></header><div className="chat-workspace"><div className="chat-list"><b>Messages</b>{connectedPeople.length ? connectedPeople.map(person => <button className={selected.name === person.name ? 'chosen' : ''} key={person.name} onClick={() => setSelected(person)}><div className="avatar" style={{ background: person.color }}>{person.avatar}</div><span><strong>{person.name}</strong><small>Connected roommate match</small></span></button>) : <p>No chats yet.</p>}</div><div className="chat-main"><header><div className="avatar" style={{ background: selected.color }}>{selected.avatar}</div><div><b>{selected.name}</b><small>Connected roommate match</small></div></header><div className="conversation"><div className="date">Today</div><p className="bubble them">Hey {profile.name.split(' ')[0]}! Glad we connected. Want to compare room preferences?</p><p className="bubble me">Absolutely — I’m usually free after 7.</p></div><form className="message" onSubmit={event => { event.preventDefault(); setMessage(''); }}><input value={message} onChange={event => setMessage(event.target.value)} placeholder="Write a message..." /><button>↑</button></form></div></div></>; }

function Settings({ profile, setProfile, tell }) { const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(profile); const [notifications, setNotifications] = useState({ requests: true, chat: true, private: false, online: true }); const [theme, setTheme] = useState('Light'); const change = (field, value) => setDraft({ ...draft, [field]: value }); const changePref = (field, value) => setDraft({ ...draft, preferences: { ...draft.preferences, [field]: value } }); const save = () => { setProfile(draft); setEditing(false); tell('Profile and compatibility updated'); }; const chooseTheme = value => { setTheme(value); document.documentElement.dataset.theme = value.toLowerCase(); tell(`${value} mode enabled`); };
 return <><header className="app-head compact"><div><p className="eyebrow">YOUR ACCOUNT</p><h1>Profile & settings</h1><p>Every profile field and preference is editable here.</p></div></header><div className="settings-grid"><section className="settings-card profile-card"><div className="avatar hero-avatar">{profile.name.split(' ').map(word => word[0]).join('').slice(0, 2)}</div><div><h2>{profile.name}</h2><p>{profile.year} · {profile.branch}</p><span className="verified">● Thapar student</span></div><button className="ghost profile-edit" onClick={() => { setDraft(profile); setEditing(!editing); }}>{editing ? 'Cancel' : 'Edit full profile'}</button></section>{editing ? <FullProfileForm draft={draft} change={change} changePref={changePref} save={save} cancel={() => setEditing(false)} /> : <ProfileSummary profile={profile} edit={() => { setDraft(profile); setEditing(true); }} />}<section className="settings-card"><h2>Notifications</h2><Toggle label="Connection requests" description="Know when someone wants to connect." value={notifications.requests} onChange={value => setNotifications({ ...notifications, requests: value })} /><Toggle label="Messages & chat" description="Get updates from your accepted matches." value={notifications.chat} onChange={value => setNotifications({ ...notifications, chat: value })} /></section><section className="settings-card"><h2>Appearance</h2><p>Choose how Roomies looks on this device.</p><div className="theme-options"><button className={theme === 'Light' ? 'theme-selected' : ''} onClick={() => chooseTheme('Light')}>☀ <b>Light</b><small>Bright and clean</small></button><button className={theme === 'Dark' ? 'theme-selected' : ''} onClick={() => chooseTheme('Dark')}>☾ <b>Dark</b><small>Easy on your eyes</small></button></div></section><section className="settings-card"><h2>Privacy</h2><Toggle label="Private profile" description="Only approved connections see your full profile." value={notifications.private} onChange={value => setNotifications({ ...notifications, private: value })} /><Toggle label="Show online status" description="Let your connections know when you’re active." value={notifications.online} onChange={value => setNotifications({ ...notifications, online: value })} /></section><section className="settings-card danger-card"><h2>Account</h2><p>Deleting your account permanently removes your profile, matches, and chats.</p><button className="danger" onClick={() => window.confirm('Delete your Roomies account permanently?') && tell('Account deletion requested')}>Delete account</button></section></div></>; }

function ProfileSummary({ profile, edit }) { return <section className="settings-card"><h2>About you <button className="text-button" onClick={edit}>Edit</button></h2><p className="bio">{profile.bio}</p><div className="pref-grid"><Preference label="Gender" value={profile.gender} /><Preference label="Year" value={profile.year} /><Preference label="Branch" value={profile.branch} /><Preference label="Hostel" value={profile.hostel} /><Preference label={profile.year === '1st year' ? 'JEE percentile' : 'CGPA'} value={profile.score} /><Preference label="Sleep style" value={profile.preferences.sleep} /><Preference label="Cleanliness" value={profile.preferences.clean} /><Preference label="Noise tolerance" value={profile.preferences.noise} /></div></section>; }

function FullProfileForm({ draft, change, changePref, save, cancel }) { const selectable = (label, field, options) => <Select label={label} value={draft.preferences[field]} options={options} onChange={value => changePref(field, value)} />; return <section className="settings-card full-editor"><h2>Edit your full profile</h2><p>Update anything—your matches will recalculate after you save.</p><h3>Personal & academic</h3><div className="editor-grid"><Field label="Full name" value={draft.name} onChange={value => change('name', value)} /><Select label="Gender" value={draft.gender} options={['Male', 'Female']} onChange={value => change('gender', value)} /><Select label="Year" value={draft.year} options={['1st year', '2nd year', '3rd year', '4th year']} onChange={value => change('year', value)} /><Select label="Branch" value={draft.branch} options={BRANCHES} onChange={value => change('branch', value)} /><Select label="Preferred hostel" value={draft.hostel} options={HOSTELS[draft.gender]} onChange={value => change('hostel', value)} /><Field label={draft.year === '1st year' ? 'JEE percentile' : 'CGPA'} value={draft.score} onChange={value => change('score', value)} /></div><Field label="About me" value={draft.bio} onChange={value => change('bio', value)} textarea /><h3>Room & lifestyle preferences</h3><div className="editor-grid">{selectable('Room type', 'roomType', ['Single', 'Double', 'No preference'])}{selectable('Roommate year', 'roommateYear', ['Same year', 'Any year', 'No preference'])}{selectable('Food preference', 'food', ['Vegetarian', 'Non-vegetarian', 'No preference'])}{selectable('Sleep schedule', 'sleep', ['Early bird', 'Flexible', 'Night owl'])}{selectable('Wake-up time', 'wake', ['5:30 AM', '6:30 AM', '7:00 AM', '8:00 AM', '9:00 AM'])}{selectable('Cleanliness', 'clean', ['Very tidy', 'Balanced', 'Relaxed'])}{selectable('Study vibe', 'study', ['Quiet focus', 'Balanced', 'Social'])}{selectable('Noise tolerance', 'noise', ['Low', 'Medium', 'High'])}</div><h3>Interests</h3><InterestPicker selected={draft.preferences.interests} onChange={value => changePref('interests', value)} /><div className="form-actions"><button className="ghost" onClick={cancel}>Cancel</button><button onClick={save}>Save & update matches</button></div></section>; }

function InterestPicker({ selected, onChange }) { const interests = ['Sports', 'Music', 'Gaming', 'Reading', 'Cooking', 'Travel', 'Movies']; return <div className="choice"><div>{interests.map(item => <button key={item} className={selected.includes(item) ? 'picked' : ''} onClick={() => onChange(selected.includes(item) ? selected.filter(value => value !== item) : [...selected, item])}>{item}</button>)}</div></div>; }
function Toggle({ label, description, value, onChange }) { return <div className="toggle-row"><div><b>{label}</b><p>{description}</p></div><button className={value ? 'toggle on' : 'toggle'} onClick={() => onChange(!value)}><i /></button></div>; }
function Preference({ label, value }) { return <div className="preference"><small>{label}</small><b>{value}</b></div>; }
function Field({ label, value, onChange, placeholder = '', type = 'text', textarea }) { return <label className="field">{label}{textarea ? <textarea value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} /> : <input type={type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} />}</label>; }
function Select({ label, value, options, onChange }) { return <label className="field">{label}<select value={value} onChange={event => onChange(event.target.value)}>{options.map(option => <option key={option}>{option}</option>)}</select></label>; }
function shortBranch(branch) { return branch.includes('Computer Engineering') ? 'COE' : branch.includes('Computer Science') ? 'CSE' : branch; }

createRoot(document.getElementById('root')).render(<App />);
